#!/bin/python3
#This script is for a Linux VM
import subprocess as sb # Lib to be able to run OS commands 

splk_password = "splunk123" #password for the admin user (This can be changed )

sb.run(["echo", "Starting the Splunk installation"])
sb.run(["wget", "-O", "splunk-9.0.4-de405f4a7979-Linux-x86_64.tgz", "https://download.splunk.com/products/splunk/releases/9.0.4/linux/splunk-9.0.4-de405f4a7979-Linux-x86_64.tgz"])
sb.run(["tar", "-zxf", "splunk-9.0.4-de405f4a7979-Linux-x86_64.tgz"])
sb.run(["sudo", "mv", "splunk", "/opt/"])
sb.run(["/opt/splunk/bin/./splunk", "start", "--accept-license","--answer-yes", "--no-prompt", "--seed-passwd", splk_password]) #Avoids the user and password request and starts the process. Make Sure port 8000 is open in the VM
